# fly.toml app configuration file generated for currency-converter-cli on 2026-05-16T22:08:37+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'currency-converter-cli'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[checks]
  [checks.alive]
    type = "http"
    interval = "30s"
    timeout = "10s"
    grace_period = "10s"
    method = "GET"
    path = "/"
